"""Initial schema

Revision ID: bf8ac61150eb
Revises: 
Create Date: 2026-01-03 01:10:02.647434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bf8ac61150eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parks_name'), table_name='parks')
    op.drop_table('parks')
    op.drop_table('park_species')
    op.drop_table('trails')
    op.drop_table('sightings')
    op.drop_table('reviews')
    op.drop_table('badges')
    op.drop_index(op.f('ix_species_name'), table_name='species')
    op.drop_index(op.f('ix_species_scientific_name'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('species_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('scientific_name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('threats', sa.VARCHAR(), nullable=True),
    sa.Column('protection_measures', sa.VARCHAR(), nullable=True),
    sa.Column('safety_guidelines', sa.VARCHAR(), nullable=True),
    sa.Column('medicinal_use', sa.VARCHAR(), nullable=True),
    sa.Column('toxicity_level', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('gallery_images', sa.VARCHAR(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(), nullable=True),
    sa.Column('video_url', sa.VARCHAR(), nullable=True),
    sa.Column('conservation_status', sa.VARCHAR(), nullable=True),
    sa.Column('habitat_type', sa.VARCHAR(), nullable=True),
    sa.Column('diet', sa.VARCHAR(), nullable=True),
    sa.Column('lifespan', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.VARCHAR(), nullable=True),
    sa.Column('weight', sa.VARCHAR(), nullable=True),
    sa.Column('best_viewing_months', sa.VARCHAR(), nullable=True),
    sa.Column('activity_time', sa.VARCHAR(), nullable=True),
    sa.Column('rarity', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('species_id')
    )
    op.create_index(op.f('ix_species_scientific_name'), 'species', ['scientific_name'], unique=False)
    op.create_index(op.f('ix_species_name'), 'species', ['name'], unique=False)
    op.create_table('badges',
    sa.Column('badge_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('icon', sa.VARCHAR(), nullable=False),
    sa.Column('requirement', sa.VARCHAR(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.INTEGER(), nullable=False),
    sa.Column('park_id', sa.INTEGER(), nullable=False),
    sa.Column('author_name', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=False),
    sa.Column('visit_date', sa.VARCHAR(), nullable=True),
    sa.Column('helpful_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('sightings',
    sa.Column('sighting_id', sa.INTEGER(), nullable=False),
    sa.Column('park_id', sa.INTEGER(), nullable=False),
    sa.Column('species_id', sa.INTEGER(), nullable=False),
    sa.Column('reporter_name', sa.VARCHAR(), nullable=False),
    sa.Column('sighting_date', sa.VARCHAR(), nullable=False),
    sa.Column('location_lat', sa.FLOAT(), nullable=False),
    sa.Column('location_lng', sa.FLOAT(), nullable=False),
    sa.Column('photo_url', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('verified', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.species_id'], ),
    sa.PrimaryKeyConstraint('sighting_id')
    )
    op.create_table('trails',
    sa.Column('trail_id', sa.INTEGER(), nullable=False),
    sa.Column('park_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(), nullable=False),
    sa.Column('length_km', sa.FLOAT(), nullable=False),
    sa.Column('duration_hours', sa.FLOAT(), nullable=False),
    sa.Column('elevation_gain', sa.INTEGER(), nullable=True),
    sa.Column('trail_type', sa.VARCHAR(), nullable=False),
    sa.Column('surface', sa.VARCHAR(), nullable=True),
    sa.Column('gpx_data', sa.VARCHAR(), nullable=True),
    sa.Column('waypoints', sa.VARCHAR(), nullable=True),
    sa.Column('highlights', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.PrimaryKeyConstraint('trail_id')
    )
    op.create_table('park_species',
    sa.Column('park_id', sa.INTEGER(), nullable=False),
    sa.Column('species_id', sa.INTEGER(), nullable=False),
    sa.Column('population_estimate', sa.VARCHAR(), nullable=True),
    sa.Column('sighting_probability', sa.VARCHAR(), nullable=True),
    sa.Column('best_spots', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.species_id'], ),
    sa.PrimaryKeyConstraint('park_id', 'species_id')
    )
    op.create_table('parks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('governorate', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('area_km2', sa.FLOAT(), nullable=True),
    sa.Column('images', sqlite.JSON(), nullable=True),
    sa.Column('google_maps_url', sa.VARCHAR(), nullable=False),
    sa.Column('hero_image_url', sa.VARCHAR(), nullable=True),
    sa.Column('gallery_images', sa.VARCHAR(), nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(), nullable=True),
    sa.Column('accessibility', sa.VARCHAR(), nullable=True),
    sa.Column('best_months', sa.VARCHAR(), nullable=True),
    sa.Column('activities', sa.VARCHAR(), nullable=True),
    sa.Column('facilities', sa.VARCHAR(), nullable=True),
    sa.Column('entrance_fee', sa.VARCHAR(), nullable=True),
    sa.Column('opening_hours', sa.VARCHAR(), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), nullable=True),
    sa.Column('area_hectares', sa.INTEGER(), nullable=True),
    sa.Column('elevation_min', sa.INTEGER(), nullable=True),
    sa.Column('elevation_max', sa.INTEGER(), nullable=True),
    sa.Column('visitor_count_yearly', sa.INTEGER(), nullable=True),
    sa.Column('average_rating', sa.FLOAT(), nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parks_name'), 'parks', ['name'], unique=False)
    # ### end Alembic commands ###
