apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # Optional: Add other datasources as needed
  # - name: InfluxDB
  #   type: influxdb
  #   access: proxy
  #   url: http://influxdb:8086
  #   database: tunisia_parks
  #   editable: true
